package com.levermann.Gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class LevermannGUI extends JFrame {
    private JScrollBar scrollBar1;
    private JTextField levermannStrategieDerEntspannteTextField;
    private JButton createDatabaseButton;
    private JButton showDatabaseButton;
    private JPanel Strategie;
    private JPanel dbfenster;
    private JPanel dberstellfenster;


    public static void main(String[] args) {
        JFrame frame = new JFrame("LevermannGUI");
        frame.setContentPane(new LevermannGUI().Strategie);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(400, 200);

        JButton createDatabaseButton = new JButton("createDatabaseButton");
    }

    public LevermannGUI() {

/*        showDatabaseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "Show now");

            }
        });

 */


        $$$setupUI$$$();
        createDatabaseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Component component = (Component) e.getSource();
                JFrame frame = (JFrame) SwingUtilities.getRoot(component);
                frame.getContentPane().setBackground(Color.BLACK);


                JOptionPane.showMessageDialog(null, "Create now");
            }
        });
        this.getContentPane().add(createDatabaseButton);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        Strategie = new Form1().getPanel();
        dbfenster = new Form2().getPanel();
        dberstellfenster = new Form3().getPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        Strategie = new JPanel();
        Strategie.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(17, 3, new Insets(0, 0, 0, 0), -1, -1));
        scrollBar1 = new JScrollBar();
        Strategie.add(scrollBar1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 16, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        levermannStrategieDerEntspannteTextField = new JTextField();
        levermannStrategieDerEntspannteTextField.setText("Levermann Strategie - Der entspannte Weg zum Reichtum");
        Strategie.add(levermannStrategieDerEntspannteTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        createDatabaseButton.setText("create Database");
        Strategie.add(createDatabaseButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        showDatabaseButton = new JButton();
        showDatabaseButton.setText("show Database");
        Strategie.add(showDatabaseButton, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Strategie;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */


}


// für die Levermannschritte ein try catch falls statt einem wert ein buchstabe übergeben wird
