package com.levermann.Gui;

import com.levermann.entityclass.HelpWindow;
import com.levermann.entityclass.Unternehmen;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ResourceBundle;

public class LevermannGUI extends JFrame {


    JMenuBar menubar;
    JMenu help;
    JMenuItem about;
    private JTextField resultsTxt;
    private JTextField Name;

    private JPanel Strategie;
    private JTextField input1;

    private JTable Unternehmen;


    public LevermannGUI() {

        setLayout(new FlowLayout());

        menubar = new JMenuBar();
        add(menubar);

        help = new JMenu("help");
        menubar.add(help);

        about = new JMenuItem("About");
        help.add(about);

        setJMenuBar(menubar);

        event e = new event();
        about.addActionListener(e);

/*

    createDatabaseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                result1.setText(input1.getText());
            }
        });
        showDatabaseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                result2.add(dbfenster);

            }
        });*/

        Unternehmen.addInputMethodListener(new InputMethodListener() {

            public boolean equals(Unternehmen unternehmen) {

                unternehmen.getName();
                return super.equals(unternehmen);
            }

            @Override
            public void inputMethodTextChanged(InputMethodEvent event) {

            }

            @Override
            public void caretPositionChanged(InputMethodEvent event) {

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Strategie = new JPanel();
        Strategie.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(18, 14, new Insets(0, 0, 0, 0), -1, -1));
        scrollBar1 = new JScrollBar();
        Strategie.add(scrollBar1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 16, 14, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        levermannStrategieDerEntspannteTextField = new JTextField();
        levermannStrategieDerEntspannteTextField.setText("Levermann Strategie - Der entspannte Weg zum Reichtum");
        Strategie.add(levermannStrategieDerEntspannteTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 14, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 25), null, 0, false));
        createDatabaseButton = new JButton();
        createDatabaseButton.setText("create Database");
        Strategie.add(createDatabaseButton, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        showDatabaseButton = new JButton();
        showDatabaseButton.setText("show Database");
        Strategie.add(showDatabaseButton, new com.intellij.uiDesigner.core.GridConstraints(4, 10, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        result1 = new JLabel();
        result1.setText("");
        Strategie.add(result1, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        result2 = new JLabel();
        result2.setText("");
        Strategie.add(result2, new com.intellij.uiDesigner.core.GridConstraints(1, 10, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dbfenster = new JPanel();
        dbfenster.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Strategie.add(dbfenster, new com.intellij.uiDesigner.core.GridConstraints(1, 11, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(88, 24), null, 0, false));
        dbfenster.setBorder(BorderFactory.createTitledBorder(ResourceBundle.getBundle("log4j").getString("heute")));
        dberstellfenster = new JPanel();
        dberstellfenster.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Strategie.add(dberstellfenster, new com.intellij.uiDesigner.core.GridConstraints(1, 7, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Unternehmen = new JTable();
        Unternehmen.putClientProperty("Datum", "");
        Unternehmen.putClientProperty("Eigenkapital", new Integer(33));
        Unternehmen.putClientProperty("Name", "Name");
        Unternehmen.putClientProperty("html.disable", Boolean.FALSE);
        Strategie.add(Unternehmen, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Strategie;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public class event implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            HelpWindow gui = new HelpWindow(LevermannGUI.this);
            gui.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            gui.setSize(300, 100);
            gui.setLocation(300, 300);
            gui.setTitle("Second Window");
            gui.setVisible(true);

        }

    }


    public static void main(String[] args) {
        LevermannGUI gui = new LevermannGUI();

        gui.setTitle("Main Window");
        gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        gui.setVisible(true);
        gui.setSize(300, 100);

    }

}


// für die Levermannschritte ein try catch falls statt einem wert ein buchstabe übergeben wird
