package com.levermann.DB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Memory {
    private static Memory INSTANCE;
    private static final String CREATE_TABLE = "CREATE TABLE company(Companyname integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY , " +
            "id float (20)  unique , datum float(11), eigenkapital float(11), jahresueberschuss float(11),  GewinnEBIT float (11), Jahresumsatz float (11)," +
            "Fremdkapital float (11), AktuellerAktienkurs float (11), Gewinnschaezung float (11),  GewinnAVG float (11),  Halten float (11)," +
            " Verkaufen float (11),\n" +
            "                             Kaufen float (11),\n" +
            "                             KursanstiegUnternehmen float (11),\n" +
            "                             KursanstiegIndex float (11),\n" +
            "                             GewinnschaezungVor4Wochen float (11),\n" +
            "                             AktienkursTagVeroeffentlichungQartalszahlen float (11),\n" +
            "                             KursVor6Monaten float (11),\n" +
            "                             KursVor12Monaten float (11),\n" +
            "                             KursVor3Monaten float (11),\n" +
            "                             KursVor2Monaten float (11),\n" +
            "                             KursVor1Monat float (11),\n" +
            "                             DaxVor1Monat float (11),\n" +
            "                             DaxVor2Monaten float (11),\n" +
            "                             DaxVor3Monaten float (11),\n" +
            "                             GewinnschaezungNaechstesJahr float (11),\n" +
            "                             GewinnschaezungDiesesJahr float (11),\n" +
            "                             Finanzsektor float (11),\n" +
            "                             PerfInJedemMonat float (11),\n" +
            "                             KursgewinnVor3Jahren float (11),\n" +
            "                             KursgewinnVor2Jahren float (11),\n" +
            "                             KursgewinnVor1Jahr float (11),\n" +
            "                             AktuellenErwartetenKursgewinn float (11),\n" +
            "                             KursgewinnschaezungNaechstesJahr float (11),;";

    private Memory(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/levermann?useSSL=false&serverTimezone=UTC", "Levermann", "Levermann");
            Statement stmnt = conn.createStatement();
            stmnt.execute(CREATE_TABLE);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public synchronized static Memory getInstance(){
        if(INSTANCE == null){
            INSTANCE = new Memory();
        }
        System.out.println("Got Instance as : " + INSTANCE);
        return INSTANCE;
    }
}
