package com.levermann.Todo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class MemoryAnalysisrating {

    private static MemoryAnalysisrating INSTANCE;
    private static final String CREATE_TABLE_ARATING = "CREATE TABLE analysisrating(Analysisrating integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY , " +
            "Companyname_AnalysisRating float(11), Eigenkapitalrendite float(11), EBITMarge float(11),  Eigenkapitalquote float (11), KursGewinnVerhaeltnis float (11)," +
            "KursGewinnVerhaeltnisAktuell float (11), Analystenmeinungen float (11), ReaktionaufQuartalszahlen float (11),  Gewinnrevision float (11),  Kursverlauf6Monate float (11)," +
            " Kursverlauf12Monate float (11),Kursmomentum float (11),Dreimonatsreversal float (11),Gewinnwachstum float (11),\n" +

            "                             Companyname_AnalysisRating float (11),\n" +
            "                             Eigenkapitalrendite float (11),\n" +
            "                             EBITMarge float (11),\n" +
            "                             Eigenkapitalquote float (11),\n" +
            "                             KursGewinnVerhaeltnis float (11),\n" +
            "                             KursGewinnVerhaeltnisAktuell float (11),\n" +
            "                             Analystenmeinungen float (11),\n" +
            "                             ReaktionaufQuartalszahlen float (11),\n" +
            "                             Gewinnrevision float (11),\n" +
            "                             Kursverlauf6Monate float (11),\n" +
            "                             Kursverlauf12Monate float (11),\n" +
            "                             Kursmomentum float (11),\n" +
            "                             Gewinnwachstum float (11),\n" +
            "                             Dreimonatsreversal float (11);";

    private MemoryAnalysisrating(){
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            Connection conn = DriverManager.getConnection("jdbc:hsqldb:mem:aname", "sa", "");
            Statement stmnt = conn.createStatement();
            stmnt.execute(CREATE_TABLE_ARATING);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public synchronized static MemoryAnalysisrating getInstance(){
        if(INSTANCE == null){
            INSTANCE = new MemoryAnalysisrating();
        }
        System.out.println("Got Instance as : " + INSTANCE);
        return INSTANCE;
    }
}
